# Generated by Django 4.1.5 on 2023-02-12 21:40

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.PositiveIntegerField()),
                ('pageCount', models.PositiveIntegerField()),
                ('pubDate', models.DateField(verbose_name='Publication Date')),
                ('genre', models.CharField(choices=[('MY', 'Mystery'), ('TH', 'Thriller'), ('CO', 'Coming of Age'), ('HI', 'Historical Fiction'), ('FA', 'Fantasy'), ('MA', 'Magical Realism'), ('LF', 'Fiction'), ('RE', 'Realistic Fiction'), ('SC', 'Science Fiction'), ('RO', 'Romance'), ('HO', 'Horror'), ('WE', 'Western'), ('DY', 'Dystopian')], max_length=2)),
                ('bookCover', models.CharField(max_length=1000)),
                ('bookColor', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#FF5722', 'deep-orange'), ('#4CAF50', 'green'), ('#03A9F4', 'light-blue'), ('#795548', 'brown')])),
            ],
        ),
    ]
