# Generated by Django 4.1.5 on 2023-02-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookColor',
        ),
    ]
