# Generated by Django 4.1.5 on 2023-02-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('MY', 'Mystery'), ('TH', 'Thriller'), ('CO', 'Coming of Age'), ('HI', 'Historical Fiction'), ('FA', 'Fantasy'), ('MA', 'Magical Realism'), ('LF', 'Literary Fiction'), ('RE', 'Realistic Fiction'), ('SC', 'Science Fiction'), ('RO', 'Romance'), ('HO', 'Horror'), ('WE', 'Western'), ('DY', 'Dystopian')], default='MY', max_length=2),
        ),
    ]
