# Generated by Django 4.1.5 on 2023-02-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birthday',
        ),
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
